# Cloudflare Pages configuration
name = "cosmic-quest-colors"
compatibility_date = "2023-10-30"

# Build settings
[build]
command = "npm run build"
output_dir = "dist"

# Environment variables
[env.production]
# Add production-specific environment variables here if needed

[env.preview]
# Add preview-specific environment variables here if needed

# Routes configuration
[routes]
include = ["/*"]
exclude = ["/assets/*"]

# Site settings
[site]
bucket = "./dist"
