[build]
command = "npm run build"
publish = "dist"
clean_urls = true

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "./dist"
entry-point = "dist/index.html"

[pages]
include = ["/*"]
exclude = []

# Enable SPA/client-side routing support
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Cache settings for static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"